Add must gather script for network observability
openshift/must-gather pull request #357
Opened 2023-04-13 15:21 UTC by msherif1234

New script to collect netobservability logs, currently not enabled by default to collect noo logs using must-gather use
```
oc adm must-gather – gather_network_observability
```

2023-04-14 06:51 UTC, jotak commented on collection-scripts/gather_network_observability
> +oc adm inspect --dest-dir "${BASE_COLLECTION_PATH}" "ns/netobserv"
"netobserv" namespace is configurable in the CRD. Can we extract that info from FlowCollector (`spec.namespace`) and inject it in this command ?

2023-04-18 14:40 UTC, jotak approved these changes
tested, lgtm
thanks @msherif1234 !

2023-04-19 09:45 UTC, jotak commented
/lgtm

2023-04-19 09:48 UTC, msherif1234 commented
/assign @davemulford

2023-04-19 17:57 UTC, msherif1234 commented
/assign @RickJWagner

2023-04-19 18:04 UTC, msherif1234 commented
/assign @sferich888

2023-04-19 18:09 UTC, davemulford commented
Since this script is being proposed to be added to the default collection of gathered items, what does this add to the archive in terms of size? What's the size on a 20+ cluster node?

2023-04-19 18:24 UTC, sferich888 requested changes
I think I would like to see the NetObserver team follow the outline set by the OpenShift logging team in that they create an independant image (or bundle the must-gather collection) with their operator image. 

https://github.com/openshift/cluster-logging-operator/tree/master/must-gather

This has several benefits: 

1. You set the pace of change that occurs with the operator and how it is debugged outside of the OCP release cadence.
2. By nesting the collection with the operator; when  'disconnected' your collection image is already mirrored as part of installation of the operator.

2023-04-19 18:24 UTC, sferich888 commented on collection-scripts/gather_network_observability
> +if [ -z "${NO_NS}" ]; then
This to me (while perfectly fine); makes me wonder if this should be part of the main must-gather collection; or if this whole collection should be part of a NetObsever collector image. 

Last I checked the NetObserver Operator is not part of the core payload; thus it has its own life cycle and release cadence; meaning that if bugs are found; that team may want to fix them (out of band of the OpenShift release cadance and cycle).  Meaning that this approach to merge the collection of thing into the main collector isn't the right approach.

2023-04-19 18:24 UTC, sferich888 commented on collection-scripts/gather_network_observability
> +    FC_NS=$(oc get ${CRD} ${obj} --output=jsonpath='{.spec.namespace}')
The scoping here is odd (I know this works in bash) but it makes code like this very hard to maintain and debug.

2023-04-19 18:24 UTC, sferich888 commented on collection-scripts/gather_network_observability
> +get_netobserv_cluster_crs
Why are we doing this vs just calling `oc admin inspect` on the cluster resource and letting [inspect](https://github.com/openshift/oc/blob/master/pkg/cli/admin/inspect/resource.go#L51) resolve the resources for the operator (including any CRD's that it defines)? 

@deads2k we may not be able to do this for OLM operators; but if that's true what can we do to fix that (we may have had this conversation before).

2023-04-19 19:42 UTC, RickJWagner approved these changes
Reads well.  I like @sferich888 comments about using a dedicated image for this purpose.  (See notes at https://github.com/openshift/enhancements/blob/master/enhancements/oc/must-gather.md#must-gather-images).
Otherwise LGTM.

2023-04-19 21:38 UTC, merged