Added SNO with workload partitioning system data gathering script
openshift/must-gather pull request #377
Opened 2023-08-21 11:54 UTC by rbaturov

This PR continues this [PR](https://github.com/openshift/must-gather/pull/373) that got accidentally merged before being reviewed.
This introduces the following changes as suggested by @sferich888 :
1. The script uses the MG namespace, not the default NS.
2.  The script now has 3-sec max sleep per node, waiting for the pod to register. (1-sec sleep each time when the pod is not yet registered). This is instead of always waiting 2 seconds unconditionally. 
Note that, in most cases, only 0-1 sec sleep will be needed, after debug pod is created.

2023-08-21 18:10 UTC, sferich888 requested changes
@soltysh there is still a lot about this I don't could you please review.

2023-08-22 13:16 UTC, rbaturov commented on collection-scripts/gather_sno
> +      oc exec "$debugPod" -n "$NAMESPACE" -- chroot /host /bin/bash -c "systemctl list-units" > "$NODES_PATH"/"$1"/list_units
No, consolidating these into 1 exec command will force us to redirect the output to one file, but we want them to be separated.

2023-08-22 13:16 UTC, rbaturov commented on collection-scripts/gather_sno
> +Collects data if workload partitioning is enabled
Definitely

2023-08-22 13:20 UTC, rbaturov commented on collection-scripts/gather_sno
> +  wait "${PIDS[@]}"
Why do you think so? I don't see why

2023-08-22 13:24 UTC, rbaturov commented on collection-scripts/gather_sno
> +NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
Then I can assume that all oc commands in the script are being executed in MG namespaces and I don't need to explicitly add the "-n "$NAMESPACE" " for each oc command?

2023-08-22 13:25 UTC, rbaturov commented on collection-scripts/gather_sno
> +      oc delete pod "$debugPod" -n "$NAMESPACE"
Ok, then I'll omit this command.

2023-08-22 13:27 UTC, rbaturov commented on collection-scripts/gather_sno
> +      sleep 1
I don't see how it's possible without this.

2023-08-22 14:08 UTC, rbaturov commented on collection-scripts/gather_sno
> +CPU_PARTITIONING=$(oc get infrastructure -o yaml | grep "CPUPartitioning" | awk '{print $2}')
Will change this to use jsonpath

2023-08-22 19:10 UTC, control-d commented on collection-scripts/gather_sno
> +      oc cp  -n "$NAMESPACE" "$debugPod":/host/etc/crio "$NODES_PATH"/"$1"/crio > /dev/null 2>&1
We collect this in sos, https://github.com/sosreport/sos/blob/4.5.6/sos/report/plugins/crio.py#L34
We also collect the active, merged config from cri-o, https://github.com/sosreport/sos/blob/4.5.6/sos/report/plugins/crio.py#L50

2023-08-23 12:51 UTC, sferich888 commented on collection-scripts/gather_sno
> +      echo "Collecting /etc/crio"
https://github.com/sosreport/sos/blob/main/sos/report/plugins/crio.py#L34 is how this is collected with sosreport.

2023-08-23 12:52 UTC, sferich888 commented on collection-scripts/gather_sno
> +      oc exec "$debugPod" -- chroot /host /bin/bash -c "systemctl list-unit-files" > "$NODES_PATH"/"$1"/list_units_files
https://github.com/sosreport/sos/blob/main/sos/report/plugins/systemd.py#L39 is how this is collected with sosreport.

2023-08-23 12:53 UTC, sferich888 commented on collection-scripts/gather_sno
> +      oc exec "$debugPod" -- chroot /host /bin/bash -c "systemctl list-units" > "$NODES_PATH"/"$1"/list_units
https://github.com/sosreport/sos/blob/main/sos/report/plugins/systemd.py#L40-L41 is how this is collected with sosreport.

2023-08-23 12:58 UTC, sferich888 commented on collection-scripts/gather_sno
> +  wait "${PIDS[@]}"
Sorry I didn't see how the Pid's were added via https://github.com/openshift/must-gather/pull/377/files#diff-f9dfc381ac5789dd0d35de5c3326c933eb63a402ca480dc22f10548b16ea891aR70

2023-08-23 13:21 UTC, sferich888 commented on collection-scripts/gather_sno
> +  for NODE in ${NODES}; do
https://issues.redhat.com/browse/RFE-3028

2023-08-23 13:23 UTC, sferich888 commented on collection-scripts/gather_sno
> +      oc exec "$debugPod" -n "$NAMESPACE" -- chroot /host /bin/bash -c "systemctl list-units" > "$NODES_PATH"/"$1"/list_units
https://access.redhat.com/solutions/3530881 and https://access.redhat.com/solutions/6577541 are the KCS docs on how to collect sosreports (for openshift) on one or multiple nodes using the `sos collect` command.

2023-10-11 11:55 UTC, sferich888 commented
@rbaturov what remains to close out the work here?

2023-12-06 19:19 UTC, sferich888 commented
@soltysh @ingvagabund I think we want to move to close this as abandoned?

2023-12-07 06:57 UTC, closed without merging