NO-ISSUE: gather additional MCO debug artifacts
openshift/must-gather pull request #468
Opened 2024-12-12 18:55 UTC by djoshy

This PR gathers a few debug artifacts pertaining to the machine-config-daemon implemented by openshift/machine-config-operator#4723 and openshift/machine-config-operator#4731. It also gathers the MachineConfiguration object, which is an singleton operator level object used to configure the MCO.

2025-01-06 13:32 UTC, djoshy commented
/test all

2025-01-06 23:08 UTC, sferich888 requested changes
I think these logs should already be collected or improvements to collect them should be worked into 'oc inspect'

2025-01-06 23:08 UTC, sferich888 commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +
This fill will not execute by default is that OK?

2025-01-06 23:08 UTC, sferich888 commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +gather_machineconfigdaemon_termination_logs
Shouldn't these logs be collected by collecting the log resources related to the pods/deployments/daemonsets (issued by oc inspect upon them)?

2025-01-06 23:22 UTC, djoshy commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +gather_machineconfigdaemon_termination_logs
Unfortunately, no. These daemonsets get recreated when the MCO rolls out an update so we tend to lose all logs related to those pods. This work involves an MCO side change which preserves the last set of daemon logs on the node to disk when the node is shutdown. We've had many customer cases where there are no "previous" logs because at the time of the must gather collection (typically post upgrade failure), the old daemonset no longer exists.

2025-01-06 23:23 UTC, djoshy commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +
Sorry, could you clarify what you mean by fill? 🙂

2025-01-06 23:30 UTC, sferich888 commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +
Will typo from my phone. In short this script has to be called explicitly not implicitly by invoking a must-gather collection with this image.

2025-01-06 23:40 UTC, djoshy commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +
Ah, I see! Will update the main script to include this one. Thanks!

2025-01-07 12:04 UTC, djoshy commented on collection-scripts/gather_machineconfigdaemon_termination_logs
> +
Updated to explicitly call from the main script! Let me know if I'm still missing something!

2025-01-09 18:22 UTC, sferich888 commented
/lgtm

2025-01-09 19:03 UTC, djoshy commented
/label acknowledge-critical-fixes-only

2025-01-09 19:07 UTC, merged